plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

title: Archie Wheeler
tagline: My personal corner of the Web.
description: A personal website containing my information, projects, and thoughts.
url: archiewheeler.com
social:
  name: Archie Wheeler
  links:
    - https://github.com/archwheeler"
    - https://www.linkedin.com/in/archie-wheeler/
locale: en_GB